FROM nvidia/cuda:11.6.1-base-ubuntu20.04

SHELL ["/bin/bash", "-c"]

WORKDIR /root

RUN apt update \
 && apt install --no-install-recommends -y curl wget git libglib2.0-0 libgl1 build-essential fonts-dejavu \
 && apt-get clean

VOLUME /root/.cache
VOLUME /res

ENV PYTHONUNBUFFERED=1
ENV GRADIO_SERVER_NAME=0.0.0.0
ENV GRADIO_SERVER_PORT=7860
EXPOSE 7860

ENV BASH_ENV=/etc/profile
ENV CONDA_DEFAULT_ENV=base

RUN mkdir ~/.conda \
 && wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh -O ~/miniconda.sh -q \
 && mkdir -p /opt \
 && bash ~/miniconda.sh -b -p /opt/conda \
 && rm ~/miniconda.sh \
 && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh \
 && echo ". /opt/conda/etc/profile.d/conda.sh" >> /etc/profile \
 && echo "conda activate \$CONDA_DEFAULT_ENV" >> /etc/profile \
 && echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc \
 && echo "conda activate \$CONDA_DEFAULT_ENV" >> ~/.bashrc \
 && find /opt/conda/ -follow -type f -name '*.a' -delete \
 && find /opt/conda/ -follow -type f -name '*.js.map' -delete \
 && /opt/conda/bin/conda clean -afy

ARG GIT_CHECKOUT=main

RUN git clone https://github.com/invoke-ai/InvokeAI.git stable-diffusion-webui \
 && cd stable-diffusion-webui \
 && git checkout $GIT_CHECKOUT \
 && conda create --name invokeai --no-default-packages --yes \
 && conda install -n invokeai pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge \
 && conda env update -n invokeai -f /root/stable-diffusion-webui/environment.yml

ENV CONDA_DEFAULT_ENV=invokeai

RUN mkdir -p /root/stable-diffusion-webui/models/ldm/stable-diffusion-v1 \
 && ln -s /res/sd-v1-4.ckpt /root/stable-diffusion-webui/models/ldm/stable-diffusion-v1/sd-v1-4.ckpt \
 && ln -s /res/v1-5-pruned-emaonly.ckpt /root/stable-diffusion-webui/models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt \
 && ln -s /res/vae-ft-mse-840000-ema-pruned.ckpt /root/stable-diffusion-webui/models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt \
 && ln -s /res/sd-v1-5-inpainting.ckpt /root/stable-diffusion-webui/models/ldm/stable-diffusion-v1/sd-v1-5-inpainting.ckpt \
 && cp /root/stable-diffusion-webui/configs/models.yaml.example /root/stable-diffusion-webui/configs/models.yaml \
 && mkdir -p /root/stable-diffusion-webui/src/gfpgan/experiments/pretrained_models \
 && ln -s /res/GFPGANv1.4.pth /root/stable-diffusion-webui/src/gfpgan/experiments/pretrained_models/GFPGANv1.4.pth \
 && mkdir -p /root/stable-diffusion-webui/ldm/invoke/restoration/codeformer/weights \
 && ln -s /res/codeformer.pth /root/stable-diffusion-webui/ldm/invoke/restoration/codeformer/weights/codeformer.pth \
 && mkdir -p /root/stable-diffusion-webui/gfpgan/weights \
 && ln -s /res/detection_Resnet50_Final.pth /root/stable-diffusion-webui/gfpgan/weights/detection_Resnet50_Final.pth \
 && ln -s /res/parsing_parsenet.pth /root/stable-diffusion-webui/gfpgan/weights/parsing_parsenet.pth \
 && echo -e "#!/bin/bash\nset -e\n[ ! -f '/root/.cache/.preloaded' ] && mkdir -p /root/.cache/.preload-weights && python /root/stable-diffusion-webui/scripts/preload_models.py && touch /root/.cache/.preloaded\nexec \"\$@\"" > /root/bootstrap.sh \
 && chmod +x /root/bootstrap.sh

WORKDIR /root/stable-diffusion-webui
ENTRYPOINT ["/root/bootstrap.sh"]
